### ISSUE TITLE
calendar does not working

### ISSUE THREAD

**Issue by aymkin** [nuriyevn/jetpms#11]
I just want to leave it here, calendar is not lading, dialog window blocking every thing on the page
![image](https://cloud.githubusercontent.com/assets/10321850/12523528/1d9cf772-c160-11e5-9e7c-4440dcc630f3.png)

**Comment by nuriyevn** [comment]
This bug is already in kanbanflow. Please, review some tools which manages both tasks and issues.
We are migrating from github immediately and kanbanflow in two 2 days.

**Comment by nuriyevn** [comment]
Please, migrate all bugs from github to kanbanflow as soon as possible.
