### ISSUE TITLE
Registration message bug

### ISSUE THREAD

**Issue by kickasska** [nuriyevn/jetpms#2]
Description
1.1 Steps to reproduce:

a) Go to http://jetpms.net/signup/index.php
b) Input email and press button 
c) Check email for activation link 
d) Click on activation link

1.2 Result:
ERR_NAME_NOT_RESOLVED
Broken Link.

1.3 Expected Resut:
Correct link with moving to the next step of registration

![registration_message_bug1](https://cloud.githubusercontent.com/assets/15984401/12198618/78648978-b61a-11e5-9b21-91705e67d88f.png)

**Comment by kickasska** [comment]
**DIR** = /var/www/html/jetpms.com
doc root = /var/www/html/jetpms.net
http host = jetpms.net
/var/www/html/jetpms.com

**Comment by kickasska** [comment]
This bug occured because of different hostname jetpms.net instead of jetpms.com.  Nusrat.

**Comment by aymkin** [comment]
В 8 утра ты ищешь баги?
09 янв. 2016 г. 7:55 пользователь "kickasska" notifications@github.com
написал:

**Comment by kickasska** [comment]
bug is fixed. Kickasska, please, confirm that bug is resolved. Nusrat.
