### ISSUE TITLE
Range calendar slidser

### ISSUE THREAD

**Issue by aymkin** [nuriyevn/jetpms#5]
1. What I do:
   logging to dashboaard.php
   or
   navigating to dashboard.php from another page (for example from accounting/index.php)
2. What do I expect:
   to see all rooms and beds + calendar with default range 15
3. What do I see:
   no calendar, just rooms and beds with width 100%

**Comment by nuriyevn** [comment]
Can't reproduce in local machine.

**Comment by nuriyevn** [comment]
Going to push to the server in order to check an issue on the server.
