### ISSUE TITLE
Leading zero

### ISSUE THREAD

**Issue by aymkin** [nuriyevn/jetpms#8]
Thx for fixing "leading zero" in calendar. I expect you to fix it in table header too.
![image](https://cloud.githubusercontent.com/assets/10321850/12419026/161a6094-bebc-11e5-9771-ecdec95cda1d.png)

**Comment by nuriyevn** [comment]
Actually it has been fixed very soon, but needs to be pushed. Thx.

**Comment by aymkin** [comment]
Это не смог сам перевести:
Actually it has been fixed very soon
Обратился к янедку :
На самом деле она была Исправлена очень скоро
И к Гугглу:
На самом деле это была зафиксирована очень скоро

Все равно не понятно. То есть скоро пофиксишь?

2016-01-19 15:28 GMT+02:00 nuriyevn notifications@github.com:

> Actually it has been fixed very soon, but needs to be pushed. Thx.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nuriyevn/jetpms/issues/8#issuecomment-172852796.

## 

Наумкин Александр
+380980238180
+380937960780
http://inhostel.org
http://vk.com/id39078995
umkin2009@ukr.net

**Comment by nuriyevn** [comment]
Сейчас запушу

**Comment by nuriyevn** [comment]
Она уже давно исправлена. только не запушена.

**Comment by nuriyevn** [comment]
Please , check

**Comment by aymkin** [comment]
Если старт календаря за три и менее дней до конца какого либо месяца, то начианется смещение, поскольку необходимо место для написания названия месяца
![image](https://cloud.githubusercontent.com/assets/10321850/12420352/cb305b5c-bec4-11e5-8ed8-713057372c92.png)

**Comment by nuriyevn** [comment]
Тоже самое можно сказать и про конец календаря.
